### ISSUE TITLE
Unable to complete installation

### ISSUE THREAD

**Issue by MorKe9986** [marianopela/MSI-GS66-Stealth#1]
Thank you very much for the Opencore.
Followed your settings. Unfortunately, the installation could not be completed. Prompt when restarting during installation
#[EB.LD.LKC|CFG] <"\\macOS Install Data\\Locked Files\\BootKernelExtensions.kc">
#[EB.LD|IN] 0 1 <"\\macOS install Data\\Locked Files\\bootKerenelExtensions.kc"><"0">
It keeps restarting

**Comment by marianopela** [comment]
Hi, did you pay close attention to this in the Readme file? 

![Screenshot 2020-12-08 at 13 12 46](https://user-images.githubusercontent.com/42821024/101482505-1f992400-3957-11eb-8064-e47a97c9f6e8.png)

You are supposed to disable CFG Lock in the advanced BIOS for best performance and stability 
(An alternative, not recommended, solution is to set `AppleXcpmCfgLock` to `True` in your config.plist

![Screenshot 2020-12-08 at 13 14 47](https://user-images.githubusercontent.com/42821024/101482793-7dc60700-3957-11eb-8dc8-1972cc46149d.png)

**Comment by MorKe9986** [comment]
> 嗨，您是否在自述文件中对此进行了密切关注？
> 
> ![截图2020-12-08 at 13 12 46](https://user-images.githubusercontent.com/42821024/101482505-1f992400-3957-11eb-8064-e47a97c9f6e8.png)
> 
> 您应该在高级BIOS中禁用CFG Lock，以获得最佳性能和稳定性 
> （一种不建议使用的替代解决方案是在config.plist中设置`AppleXcpmCfgLock`为`True`
> 
> ![截图2020-12-08 at 13 14 47](https://user-images.githubusercontent.com/42821024/101482793-7dc60700-3957-11eb-8dc8-1972cc46149d.png)

Yes. I have set CFG Lock to disable. You can enter the installation interface during installation. The installation progress bar also runs again. However, it restarts automatically and prompts an error code in the middle of the installation. 
The installation version I use: Big Sur 11.0.1 (20B50)
My GS66 configuration: i7 10750H-RTX2060-16G-1T Nvme
error report:
![故障报告](https://user-images.githubusercontent.com/54764963/101969523-ba4b7880-3c5f-11eb-80dd-e27dc422b681.jpg)

**Comment by marianopela** [comment]
A stupid question: did you format the drive to APFS?

**Comment by MorKe9986** [comment]
> 一个愚蠢的问题：您是否将驱动器格式化为APFS？

Oh! Surprisingly, when I changed a disk as the installation medium it was fine. Now successfully installed

**Comment by marianopela** [comment]
Good to know! I can close the issue, then
